# Generated by Django 5.2.7 on 2025-10-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default=None, max_length=50)),
                ('department_no_of_projects', models.IntegerField(default=None)),
                ('department_head', models.CharField(default=None, max_length=30)),
                ('department_region', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
