# Generated by Django 5.2.7 on 2025-10-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default=None, max_length=50)),
                ('employee_age', models.CharField(default=None, max_length=30)),
                ('employee_address', models.CharField(default=None, max_length=100)),
                ('employee_department', models.CharField(default=None, max_length=30)),
                ('employee_reporting_manager', models.CharField(default=None, max_length=50)),
                ('employee_email', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
